FROM docker.ermao.net/mlikiowa/napcat-docker:latest

# 基础登录配置
ENV NAPCAT_QQ=2647742870
ENV NAPCAT_LOGIN_METHOD=qrcode
ENV NAPCAT_QRCODE_TIMEOUT=180
ENV NAPCAT_AUTO_LOGIN=true

# OneBot反向WS客户端配置
ENV NAPCAT_REVERSE_WS_CLIENT_ENABLE=true
ENV NAPCAT_REVERSE_WS_CLIENT_URL=wss://ermaozi.cn/onebot/v11/ws
ENV NAPCAT_ONE_BOT_COMPATIBLE=true
ENV NAPCAT_WS_RECONNECT=true
ENV NAPCAT_WS_RECONNECT_INTERVAL=5
ENV NAPCAT_WS_TIMEOUT=30

# 性能优化
ENV NAPCAT_DISABLE_DOCKER_OPS=true
ENV ELECTRON_DISABLE_GPU=true
ENV NODE_ENV=production

WORKDIR /app
RUN mkdir -p /app/napcat/config /app/.config/QQ
RUN chown -R 1000:1000 /app
USER 1000:1000